export const CURSOS = [
  "Todos",
  "Administração",
  "Biomedicina",
  "Ciência da Computação",
  "Ciências Contábeis",
  "Direito",
  "Educação Física",
  "Enfermagem",
  "Engenharia Civil",
  "Farmácia",
  "Fisioterapia",
  "Pedagogia",
  "Psicologia",
  "Recursos Humanos",
  "Tecnologia da Informação",
];
