name: Deployment
run-name: ${{github.actor}} está aprendendo github actions.

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - run: npm install -g bats
      - run: bats -v
